config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'weapons#index'

  resources :users, only: %i[index create]
  resources :weapons
  resources :enemies, only: %i[update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/enemy.rb
class Enemy < ApplicationRecord
  enum kind: { goblin: 0, orc: 1, demon: 2, dragons: 3 }
  validates :level, numericality: { greather_than: 0, less_than_or_equal_to: 99 }
  validates :name, :power_base, :power_step, :level, :kind, presence: true

  def current_power
    (power_base + ((level - 1) * power_step))
  end
end

app/models/user.rb
# frozen_string_literal: true

# Class User, the Hero
class User < ApplicationRecord
  enum kind: { knight: 0, wizard: 1 }

  validates :level, numericality: { greather_than: 0, less_than_or_equal_to: 99 }

  def title
    "#{kind} #{nickname} ##{level}"
  end
end

app/models/weapon.rb
# frozen_string_literal: true

class Weapon < ApplicationRecord
  validates :level, numericality: { greather_than: 0, less_than_or_equal_to: 99 }
  # validates :name, presence: true, length: { minimum: 3 }

  def current_power
    (power_base + ((level - 1) * power_step))
  end

  def title
    "#{name} #{level}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enemies_controller.rb
class EnemiesController < ApplicationController
  def update
    if @enemy.update(enemy_params)
      render json: @enemy, status: :ok
    else
      render json: { erros: @enemy.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    @enemy.destroy
    head :no_content
  end

  before_action :set_enemy

  private

  def enemy_params
    params.permit(:name, :power_base, :power_step, :level, :kind)
  end

  def set_enemy
    @enemy = Enemy.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    render json: { message: e.message }, status: :not_found
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.create(user_params)
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :kind, :level)
  end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  def index
    @weapons = Weapon.all
  end

  def create
    @weapon = Weapon.create(weapon_params)
    redirect_to weapons_path
  end

  def destroy
    @weapon = Weapon.find(params[:id])
    @weapon.destroy

    redirect_to root_path, status: :see_other
  end

  def show
    @weapon = Weapon.find(params[:id])
  end

  private

  def weapon_params
    params.require(:weapon).permit(
      :name, :description, :power_base, :power_step, :level
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/enemies/destroy.html.erb
<h1>Enemies#destroy</h1>
<p>Find me in app/views/enemies/destroy.html.erb</p>

app/views/enemies/update.html.erb
<h1>Enemies#update</h1>
<p>Find me in app/views/enemies/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestLikeAHero</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<% @users.each do |user| %>
<p><%= user.title%></p>
<% end %>

app/views/weapons/create.html.erb
<h1>Weapons#create</h1>
<p>Find me in app/views/weapons/create.html.erb</p>

app/views/weapons/index.html.erb
<h1>Weapons#index</h1>
<p>Find me in app/views/weapons/index.html.erb</p>

<h2>All Weanpos</h2>
<ul>
  <% @weapons.each do |weapon| %>
    <li>
      <p><%= weapon.name %><p>
      <ul>
        <li><%= weapon.current_power %></li>
        <li><%= weapon.title %></li>
        <li><%= link_to 'details', weapon %></li>
      </ul>
    </li>
  <% end %>
</ul>
  

app/views/weapons/show.html.erb
<h1>Weapons#show</h1>
<p>Find me in app/views/weapons/show.html.erb</p>

<h1><%= @weapon.name %></h1>
<p>Description:<%= @weapon.description %></p>
<p>Power Base:<%= @weapon.power_base %></p>
<p>Power Step:<%= @weapon.power_step %></p>
<p>Current Power:<%= @weapon.current_power %></p>
<p>Level:<%= @weapon.level %></p>

<ul>
  <li><%= link_to "Back", weapons_path %></li>  
  <li><%= link_to "Destroy", weapon_path(@weapon), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
</ul>